#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Post-processing fixer for existing .md files generated by md_maker.py.

Fixes four known conversion bugs:
  1. Condensed paragraphs in :::note blocks (single line → multi-paragraph)
  2. :::note blocks at wrong indent (inside list vs. top-level)
  3. Images at wrong indent within list items
  4. HTML tables with broken indent (collapses multi-line <pre> blocks, re-indents)

Usage:
  python fix-md.py <prod_url>                          # fix single page
  python fix-md.py <prod_url> --crawl                  # fix all pages in the guide
  python fix-md.py <prod_url> --crawl --limit 10       # fix first 10 pages
  python fix-md.py <prod_url> --crawl --limit 10-20   # fix pages 10 through 20
  python fix-md.py <prod_url> --crawl --dry-run        # preview all fixes

Requires: requests, beautifulsoup4
Optional: playwright (for client-rendered pages)
"""

import re
import sys
import os
import time
import argparse
import urllib.parse
from typing import List, Dict, Tuple, Optional

import requests
from bs4 import BeautifulSoup, Tag, NavigableString

THROTTLE_SECONDS = 1.0
FETCH_RETRIES = 3
FETCH_TIMEOUT = 30
CODE_IN_TABLE_THRESHOLD = 60  # inline code length that triggers md→HTML table conversion

# ---------------------------------------------------------------------------
# Logging — collects all output for the summary report
# ---------------------------------------------------------------------------

_log_lines: List[str] = []


def _log(msg: str):
    """Print and record a message."""
    print(msg)
    _log_lines.append(msg)


# ---------------------------------------------------------------------------
# Prod HTML fetching
# ---------------------------------------------------------------------------

_SESSION: Optional[requests.Session] = None

def _get_session() -> requests.Session:
    global _SESSION
    if _SESSION is None:
        _SESSION = requests.Session()
        _SESSION.headers["User-Agent"] = "UiPathDocsFixer/1.0"
    return _SESSION


def fetch_page(url: str) -> Tuple[Optional[Tag], Optional[BeautifulSoup]]:
    """Fetch a prod page with retries. Returns (container, full_soup)."""
    session = _get_session()
    for attempt in range(1, FETCH_RETRIES + 1):
        try:
            resp = session.get(url, timeout=FETCH_TIMEOUT)
            resp.raise_for_status()
            break
        except requests.RequestException as e:
            if attempt < FETCH_RETRIES:
                wait = attempt * 2
                _log(f"  [retry] Attempt {attempt}/{FETCH_RETRIES} failed for {url}: {e}")
                _log(f"          Retrying in {wait}s...")
                time.sleep(wait)
            else:
                _log(f"  [error] Failed to fetch {url} after {FETCH_RETRIES} attempts: {e}")
                return None, None

    soup = BeautifulSoup(resp.content, "html.parser")
    container = soup.find(id="DocContainer")
    if not container:
        container = soup.find("main") or soup.find("article") or soup.body

    if container and container.get_text(strip=True):
        return container, soup

    # Fallback: Playwright for client-rendered content
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            browser = p.chromium.launch(headless=True)
            page = browser.new_page()
            page.goto(url, wait_until="networkidle", timeout=30000)
            page.wait_for_selector("#DocContainer", timeout=15000)
            html = page.content()
            browser.close()
        soup_pw = BeautifulSoup(html, "html.parser")
        container_pw = soup_pw.find(id="DocContainer") or soup_pw.body
        return container_pw, soup_pw
    except Exception as e:
        _log(f"  [warn] Playwright fallback failed: {e}")
        return container, soup


def fetch_prod_html(url: str) -> Optional[Tag]:
    """Fetch prod page and return just the content container."""
    container, _ = fetch_page(url)
    return container


# ---------------------------------------------------------------------------
# Guide crawling
# ---------------------------------------------------------------------------

def discover_guide_urls(start_url: str, max_pages: int = 0) -> List[str]:
    """Crawl a guide starting from start_url and return all page URLs.

    Args:
        max_pages: Stop discovering after this many pages (0 = unlimited).
    """
    parsed = urllib.parse.urlparse(start_url)
    # Base = everything up to (but not including) the last segment
    path_parts = parsed.path.rstrip("/").rsplit("/", 1)
    base_url = parsed.scheme + "://" + parsed.netloc + path_parts[0] + "/"

    visited = set()
    queue = [start_url]
    ordered = []

    _log(f"Discovering guide pages under: {base_url}")
    if max_pages > 0:
        _log(f"  (limited to {max_pages} page(s))")

    while queue:
        if max_pages > 0 and len(ordered) >= max_pages:
            break

        url = urllib.parse.urldefrag(queue.pop(0))[0]
        if url in visited:
            continue
        visited.add(url)
        ordered.append(url)

        _, soup = fetch_page(url)
        if not soup:
            continue

        time.sleep(THROTTLE_SECONDS)

        for a in soup.find_all("a", href=True):
            href = a["href"]
            if href.startswith("#") or href.startswith("mailto:"):
                continue
            abs_url = urllib.parse.urldefrag(urllib.parse.urljoin(url, href))[0]
            if abs_url.startswith(base_url) and abs_url not in visited:
                queue.append(abs_url)

    _log(f"  Found {len(ordered)} page(s)\n")
    return ordered


# ---------------------------------------------------------------------------
# Prod structure extraction
# ---------------------------------------------------------------------------

def extract_prod_structure(container: Tag) -> dict:
    """Extract structural info from prod HTML: notes, images, list items, inline paragraphs."""
    structure = {
        "notes": [],       # [{"in_list": bool, "li_depth": int, "text_preview": str}]
        "images": [],      # [{"in_list": bool, "li_depth": int, "src": str}]
        "list_items": [],  # [{"depth": int, "text": str, "has_note": bool}]
        "li_paragraphs": [],  # paragraphs/divs inside <li> that md_maker may orphan
        "tables": [],      # [{"in_list": bool, "li_depth": int, "text_preview": str}]
        "headings": [],    # [{"level": int, "text": str}]
        "paragraphs": [],  # [{"text": str}]  — top-level paragraphs (not in lists/tables/notes)
    }

    ADMON_CLASSES = {"note", "warning", "important", "information", "tip", "danger"}

    # Extract note/admonition positions
    for div in container.find_all("div", class_=True):
        classes = set(div.get("class", []))
        if "note" not in classes and not ADMON_CLASSES & classes:
            continue
        li_parent = div.find_parent("li")
        depth = _li_depth(li_parent) if li_parent else -1
        text = div.get_text(strip=True)[:80]
        # Collect direct-child <p> elements (not inside <ul>/<ol>/<li>)
        # to locate paragraph breaks.  <p> inside list items are bullet
        # content, not standalone paragraphs.
        para_starts = []
        direct_p_count = 0
        for p in div.find_all("p"):
            # Check if this <p> is inside a list within the note
            list_ancestor = p.find_parent(["ul", "ol"])
            if list_ancestor and div in list_ancestor.parents:
                continue  # inside a list — skip
            p_text = re.sub(r'\s+', ' ', p.get_text(strip=True))
            if p_text:
                para_starts.append(p_text[:60])
                direct_p_count += 1
        structure["notes"].append({
            "in_list": li_parent is not None,
            "li_depth": depth,
            "text_preview": text,
            "paragraphs": direct_p_count,
            "para_starts": para_starts,
        })

    # Extract image positions — only block-level images (not inline icons).
    # An image is inline if its immediate block-level ancestor (p, li, td)
    # contains significant text besides the image.
    for img in container.find_all("img"):
        src = img.get("src", "")
        block = img.parent
        while block and block.name not in ("p", "li", "td", "div", "body"):
            block = block.parent
        if block and block.name in ("p", "li"):
            sibling_text = ""
            for sib in block.children:
                if sib is img:
                    continue
                if isinstance(sib, NavigableString):
                    sibling_text += str(sib).strip()
                elif hasattr(sib, "get_text") and sib.name not in ("style", "script"):
                    if not sib.find("img"):
                        sibling_text += sib.get_text(strip=True)
            if len(sibling_text) > 5:
                continue  # inline icon — skip

        li_parent = img.find_parent("li")
        depth = _li_depth(li_parent) if li_parent else -1
        structure["images"].append({
            "in_list": li_parent is not None,
            "li_depth": depth,
            "src": src,
        })

    # Extract list items
    for li in container.find_all("li"):
        depth = _li_depth(li)
        # Check if this li directly contains a note
        has_note = any(
            div for div in li.find_all("div", class_=True, recursive=False)
            if {"note"} & set(div.get("class", []))
            or ADMON_CLASSES & set(div.get("class", []))
        )
        # Also check in itemgroup info children
        for info_div in li.find_all("div", class_="itemgroup"):
            if any(
                div for div in info_div.find_all("div", class_=True, recursive=False)
                if ADMON_CLASSES & set(div.get("class", []))
            ):
                has_note = True

        text = _li_text(li)
        structure["list_items"].append({
            "depth": depth,
            "text": text,
            "has_note": has_note,
        })

    # Extract paragraphs/divs inside <li> that may get orphaned by md_maker.
    # These are block children (p, div) of a <li> that contain text and are
    # followed by or preceded by a sub-list.
    for li in container.find_all("li"):
        li_first_text = ""
        # Get the first text content of the li (the list item head)
        for child in li.children:
            if isinstance(child, NavigableString) and child.strip():
                li_first_text = child.strip()[:80]
                break
            if isinstance(child, Tag) and child.name in ("span", "p", "a", "strong", "em", "b"):
                li_first_text = child.get_text(strip=True)[:80]
                break

        for child in li.children:
            if not isinstance(child, Tag):
                continue
            if child.name in ("ul", "ol"):
                continue
            # Skip admonition divs
            cls = child.get("class") if child.attrs else None
            if cls and ADMON_CLASSES & set(cls or []):
                continue
            # Look for block elements with text that are siblings of sub-lists
            if child.name in ("div", "p") and child.get_text(strip=True):
                child_text = re.sub(r'\s+', ' ', child.get_text(strip=True))
                # Skip if this is the same as the first text (it's the li head itself)
                if child_text[:60] == li_first_text[:60]:
                    continue
                structure["li_paragraphs"].append({
                    "li_head": li_first_text,
                    "text": child_text[:120],
                    "li_depth": _li_depth(li),
                })

    # Extract HTML tables
    for table in container.find_all("table"):
        li_parent = table.find_parent("li")
        depth = _li_depth(li_parent) if li_parent else -1
        first_row = table.find("tr")
        preview = first_row.get_text(strip=True)[:80] if first_row else ""
        # Extract table headers and row count for structural comparison
        headers = []
        header_row = table.find("tr")
        if header_row:
            for th in header_row.find_all(["th", "td"]):
                headers.append(re.sub(r'\s+', ' ', th.get_text(strip=True)))
        rows = table.find_all("tr")
        structure["tables"].append({
            "in_list": li_parent is not None,
            "li_depth": depth,
            "text_preview": preview,
            "element": table,
            "headers": headers,
            "row_count": len(rows),
            "col_count": len(headers),
        })

    # Extract headings (h1-h4) for structural comparison
    for h in container.find_all(["h1", "h2", "h3", "h4"]):
        level = int(h.name[1])
        text = re.sub(r'\s+', ' ', h.get_text(strip=True))
        # Strip trailing "link" text from anchor links
        text = re.sub(r'\s*link$', '', text)
        structure["headings"].append({"level": level, "text": text})

    # Extract top-level paragraphs (not inside tables, lists, or admonitions)
    ADMON_CLASSES_P = {"note", "warning", "important", "information", "tip", "danger"}
    for p in container.find_all("p"):
        # Skip if inside a table, list, or admonition
        if p.find_parent("table"):
            continue
        if p.find_parent(["ul", "ol"]):
            continue
        admon_parent = p.find_parent("div", class_=True)
        if admon_parent and ADMON_CLASSES_P & set(admon_parent.get("class", [])):
            continue
        text = re.sub(r'\s+', ' ', p.get_text(strip=True))
        if text and len(text) > 10:
            # Skip footnote paragraphs (start with superscript number)
            if re.match(r'^\d+[A-Z]', text) and p.find("sup"):
                continue
            structure["paragraphs"].append({"text": text})

    return structure


def _li_depth(li: Tag) -> int:
    """Count nesting depth of a <li> element."""
    depth = 0
    parent = li.parent
    while parent:
        if parent.name == "li":
            depth += 1
        parent = parent.parent
    return depth


def _li_text(li: Tag) -> str:
    """Get the direct text of a <li>, excluding sub-lists and notes."""
    clone = BeautifulSoup(str(li), "html.parser").find("li")
    if not clone:
        return ""
    for sub in clone.find_all(["ul", "ol"]):
        sub.decompose()
    ADMON = {"note", "warning", "important", "information", "tip", "danger"}
    for div in list(clone.find_all("div")):
        cls = div.get("class") if div.attrs else None
        if cls and ADMON & set(cls):
            div.decompose()
    return re.sub(r'\s+', ' ', clone.get_text(strip=True))[:120]


# ---------------------------------------------------------------------------
# Markdown structure extraction
# ---------------------------------------------------------------------------

def parse_md_structure(lines: List[str]) -> dict:
    """Extract structural info from markdown lines."""
    structure = {
        "notes": [],    # [{"line": int, "indent": int, "in_list": bool, "end_line": int, "paragraph_count": int}]
        "images": [],   # [{"line": int, "indent": int}]
        "list_items": [],
        "orphaned_paragraphs": [],  # paragraphs at indent 0 between list items
        "tables": [],   # [{"start_line": int, "end_line": int, "indent": int, "text_preview": str}]
        "md_pipe_tables": [],  # markdown pipe tables with long code cells
        "headings": [],  # [{"line": int, "level": int, "text": str}]
        "paragraphs": [],  # [{"line": int, "text": str}]  — top-level paragraphs
        "frontmatter_title": "",  # title from YAML frontmatter
    }

    fence_open = re.compile(r'^(\s*):::(note|tip|warning|danger|info|important|caution)\s*$')
    fence_close = re.compile(r'^(\s*):::\s*$')
    image_re = re.compile(r'^(\s*)!\[')
    list_head = re.compile(r'^(\s*)([-*+]|\d+\.)\s+')
    code_fence = re.compile(r'^\s*(```|~~~)')

    inside_code = False
    i = 0
    n = len(lines)

    # Track list context
    list_stack = []  # [(indent, marker_len)]

    while i < n:
        line = lines[i]

        if code_fence.match(line):
            inside_code = not inside_code
            i += 1
            continue

        if inside_code:
            i += 1
            continue

        # Track list items
        m_list = list_head.match(line)
        if m_list:
            indent = len(m_list.group(1))
            marker = m_list.group(2)
            # Pop items at same or deeper indent
            while list_stack and list_stack[-1][0] >= indent:
                list_stack.pop()
            list_stack.append((indent, len(marker) + 1))
            structure["list_items"].append({
                "line": i,
                "indent": indent,
                "depth": len(list_stack) - 1,
                "text": line.strip()[:120],
            })

        # Detect ::: note blocks
        m_open = fence_open.match(line)
        if m_open:
            note_indent = len(m_open.group(1))
            start = i
            para_count = 0
            has_content = False
            j = i + 1
            while j < n and not fence_close.match(lines[j]):
                if lines[j].strip():
                    if not has_content or (j > 0 and not lines[j - 1].strip()):
                        para_count += 1
                    has_content = True
                j += 1
            end = j

            in_list = bool(list_stack) and note_indent > 0
            structure["notes"].append({
                "line": start,
                "end_line": end,
                "indent": note_indent,
                "in_list": in_list,
                "paragraph_count": para_count,
                "admonition_type": m_open.group(2),
            })
            i = end + 1
            continue

        # Detect images
        m_img = image_re.match(line)
        if m_img:
            img_indent = len(m_img.group(1))
            in_list = bool(list_stack)
            structure["images"].append({
                "line": i,
                "indent": img_indent,
                "in_list": in_list,
            })

        i += 1

    # Detect HTML <table> blocks
    table_open_re = re.compile(r'^(\s*)<table', re.I)
    table_close_re = re.compile(r'^\s*</table>', re.I)
    in_code_tbl = False
    for i, line in enumerate(lines):
        if code_fence.match(line):
            in_code_tbl = not in_code_tbl
            continue
        if in_code_tbl:
            continue
        m_tbl = table_open_re.match(line)
        if m_tbl:
            tbl_indent = len(m_tbl.group(1))
            # Find the matching </table>
            end_idx = i
            for j in range(i + 1, n):
                if table_close_re.match(lines[j]):
                    end_idx = j
                    break
            # Get text preview from first row and extract headers/row count
            preview = ""
            tbl_html = "\n".join(lines[i:end_idx + 1])
            tbl_soup = BeautifulSoup(tbl_html, "html.parser")
            tbl_tag = tbl_soup.find("table")
            md_headers = []
            md_row_count = 0
            if tbl_tag:
                first_tr = tbl_tag.find("tr")
                if first_tr:
                    for th in first_tr.find_all(["th", "td"]):
                        md_headers.append(re.sub(r'\s+', ' ', th.get_text(strip=True)))
                md_row_count = len(tbl_tag.find_all("tr"))
                preview = first_tr.get_text(strip=True)[:80] if first_tr else ""
            structure["tables"].append({
                "start_line": i,
                "end_line": end_idx,
                "indent": tbl_indent,
                "text_preview": preview,
                "headers": md_headers,
                "row_count": md_row_count,
                "col_count": len(md_headers),
            })

    # Detect markdown pipe tables with long inline code cells
    md_pipe_re = re.compile(r'^\s*\|')
    md_sep_re = re.compile(r'^\s*\|([\s:]*-+[\s:]*\|)+\s*$')
    long_code_re = re.compile(r'`{1,3}\s*(.+?)\s*`{1,3}')
    in_code_pipe = False
    i_pipe = 0
    while i_pipe < n:
        ln = lines[i_pipe]
        if code_fence.match(ln):
            in_code_pipe = not in_code_pipe
            i_pipe += 1
            continue
        if in_code_pipe:
            i_pipe += 1
            continue
        if md_pipe_re.match(ln) and i_pipe + 1 < n and md_sep_re.match(lines[i_pipe + 1]):
            tbl_start = i_pipe
            tbl_indent = len(ln) - len(ln.lstrip())
            j = i_pipe + 2
            while j < n and md_pipe_re.match(lines[j]):
                j += 1
            tbl_end = j - 1
            # Check if any cell has long inline code
            has_long_code = False
            for k in range(tbl_start, tbl_end + 1):
                if k == tbl_start + 1:
                    continue  # separator row
                for m in long_code_re.finditer(lines[k]):
                    if len(m.group(1).strip()) >= CODE_IN_TABLE_THRESHOLD:
                        has_long_code = True
                        break
                if has_long_code:
                    break
            if has_long_code:
                structure["md_pipe_tables"].append({
                    "start_line": tbl_start,
                    "end_line": tbl_end,
                    "indent": tbl_indent,
                })
            i_pipe = tbl_end + 1
        else:
            i_pipe += 1

    # Detect headings and top-level paragraphs for structural comparison
    heading_detect_re = re.compile(r'^(#{1,6})\s+(.*)')
    in_code_hp = False
    in_table_hp = False
    in_note_hp = False
    in_frontmatter = False
    frontmatter_done = False
    table_open_hp = re.compile(r'^\s*<table', re.I)
    table_close_hp = re.compile(r'^\s*</table>', re.I)
    note_open_hp = re.compile(r'^\s*:::\w+')
    note_close_hp = re.compile(r'^\s*:::\s*$')
    for i_hp, line_hp in enumerate(lines):
        # Skip YAML frontmatter (--- ... ---)
        if not frontmatter_done:
            if i_hp == 0 and line_hp.strip() == '---':
                in_frontmatter = True
                continue
            if in_frontmatter:
                if line_hp.strip() == '---':
                    in_frontmatter = False
                    frontmatter_done = True
                else:
                    # Extract title from frontmatter
                    m_title = re.match(r'^title:\s*(.+)', line_hp)
                    if m_title:
                        structure["frontmatter_title"] = m_title.group(1).strip().strip('"').strip("'")
                continue
            frontmatter_done = True
        if code_fence.match(line_hp):
            in_code_hp = not in_code_hp
            continue
        if in_code_hp:
            continue
        if table_open_hp.match(line_hp):
            in_table_hp = True
            continue
        if table_close_hp.match(line_hp):
            in_table_hp = False
            continue
        if in_table_hp:
            continue
        if note_open_hp.match(line_hp) and not note_close_hp.match(line_hp):
            in_note_hp = True
            continue
        if note_close_hp.match(line_hp):
            in_note_hp = False
            continue
        if in_note_hp:
            continue
        m_head = heading_detect_re.match(line_hp)
        if m_head:
            structure["headings"].append({
                "line": i_hp,
                "level": len(m_head.group(1)),
                "text": m_head.group(2).strip(),
            })
            continue
        # Top-level paragraphs: non-blank, not indented, not a list item, not a heading,
        # not inside code/table/note, not frontmatter, not HTML tags
        stripped_hp = line_hp.strip()
        first_ch = line_hp[0:1] if line_hp else ''
        # Exclude lines starting with whitespace, heading markers, pipe, image,
        # or HTML tags.  For *, -, + only exclude if it's a list item (char + space),
        # not bold (**text**) or other inline usage.
        if first_ch in (' ', '\t', '#', '|', '!', '<'):
            continue
        if first_ch in ('*', '-', '+') and len(line_hp) > 1 and line_hp[1:2] in (' ', '\t'):
            continue  # list item
        if (stripped_hp
                and not stripped_hp.startswith('---')
                and not list_head.match(line_hp)
                and len(stripped_hp) > 10
                and not re.match(r'^\d+\.?\s', stripped_hp)):
            structure["paragraphs"].append({
                "line": i_hp,
                "text": stripped_hp,
            })

    # Detect orphaned paragraphs: non-blank lines at indent 0 that sit
    # between a list item and its sub-items or the next list item.
    heading_re = re.compile(r'^#{1,6}\s')
    fence_open_admon = re.compile(r'^\s*:::\w+')
    list_head_re = re.compile(r'^(\s*)([-*+]|\d+\.)\s+')
    code_fence_re = re.compile(r'^\s*(```|~~~)')
    in_code = False

    for i, line in enumerate(lines):
        if code_fence_re.match(line):
            in_code = not in_code
            continue
        if in_code:
            continue
        if not line.strip():
            continue
        # Must be at indent 0, not a list item, heading, fence, image, or table
        if line[0] == ' ' or line[0] == '\t':
            continue
        if list_head_re.match(line):
            continue
        if heading_re.match(line):
            continue
        if fence_open_admon.match(line):
            continue
        if line.startswith('!['):
            continue
        if line.startswith('|'):
            continue
        if line.startswith('---'):
            continue

        # Look backwards: is there a list item before this (skipping blanks)?
        prev_list_line = None
        for k in range(i - 1, -1, -1):
            if not lines[k].strip():
                continue
            if list_head_re.match(lines[k]):
                prev_list_line = k
            break

        if prev_list_line is None:
            continue

        # Look forwards: is there a list item or sub-item after (skipping blanks)?
        next_list_line = None
        for k in range(i + 1, len(lines)):
            if not lines[k].strip():
                continue
            if list_head_re.match(lines[k]):
                next_list_line = k
            break

        if next_list_line is None:
            continue

        # This paragraph is sandwiched between list items — it's orphaned
        text = re.sub(r'\s+', ' ', line.strip())
        structure["orphaned_paragraphs"].append({
            "line": i,
            "text": text[:120],
            "prev_list_line": prev_list_line,
        })

    return structure


# ---------------------------------------------------------------------------
# Fix functions
# ---------------------------------------------------------------------------

def fix_note_indent(lines: List[str], md_note: dict, prod_note: dict) -> List[str]:
    """Fix a note's indentation based on prod structure."""
    start = md_note["line"]
    end = md_note["end_line"]
    current_indent = md_note["indent"]

    if prod_note["in_list"]:
        # Note should be inside a list item — find the correct indent
        # Look backwards for the parent list item
        target_indent = _find_list_cont_indent(lines, start)
        if target_indent is not None and target_indent != current_indent:
            _log(f"  [fix] Note at line {start + 1}: indent {current_indent} -> {target_indent}")
            for k in range(start, min(end + 1, len(lines))):
                stripped = lines[k].lstrip(' ')
                lines[k] = ' ' * target_indent + stripped
    else:
        # Note should be top-level (indent 0)
        if current_indent > 0:
            _log(f"  [fix] Note at line {start + 1}: indent {current_indent} -> 0 (top-level)")
            for k in range(start, min(end + 1, len(lines))):
                lines[k] = lines[k].lstrip(' ')

    return lines


def fix_note_paragraphs(lines: List[str], md_note: dict, prod_note: dict) -> List[str]:
    """Fix condensed paragraphs in a note block.

    When md_maker strips <p> tags inside admonitions, multiple paragraphs
    get condensed onto one line.  We use the first words of each prod <p>
    to locate paragraph boundaries in the md content and insert blank lines.
    """
    if prod_note["paragraphs"] <= 1:
        return lines
    if md_note["paragraph_count"] >= prod_note["paragraphs"]:
        return lines

    para_starts = prod_note.get("para_starts", [])
    if len(para_starts) < 2:
        _log(f"  [warn] Note at line {md_note['line'] + 1}: has {md_note['paragraph_count']} paragraph(s) "
              f"but prod has {prod_note['paragraphs']}. Could not extract paragraph starts.")
        return lines

    start = md_note["line"]      # :::note line
    end = md_note["end_line"]    # ::: closing line
    indent = md_note["indent"]

    # Gather the note's content lines (between ::: fences)
    content_lines = []
    for k in range(start + 1, end):
        content_lines.append((k, lines[k]))

    if not content_lines:
        return lines

    # Join all content into one string to search for paragraph starts
    # We need to map positions in the joined string back to line indices
    joined = ""
    line_boundaries = []  # (start_pos_in_joined, line_idx)
    for line_idx, text in content_lines:
        stripped = text.strip()
        if not stripped:
            # Already a blank line — keep track but skip in search
            line_boundaries.append((len(joined), line_idx, True))
            continue
        if joined:
            joined += " "
        line_boundaries.append((len(joined), line_idx, False))
        joined += stripped

    # Normalize for matching
    joined_norm = re.sub(r'\s+', ' ', joined).strip()

    # Find where each paragraph starts in the joined text
    # Skip para_starts[0] — that's the beginning of the note
    split_positions = []  # char positions in joined_norm where a new paragraph starts
    for ps in para_starts[1:]:
        ps_norm = re.sub(r'\s+', ' ', ps).strip()
        # Try progressively shorter prefixes for fuzzy matching
        found = False
        for trim in range(0, max(0, len(ps_norm) - 10), 5):
            needle = ps_norm[:len(ps_norm) - trim] if trim else ps_norm
            if len(needle) < 10:
                break
            pos = joined_norm.find(needle)
            if pos > 0:
                split_positions.append(pos)
                found = True
                break
        if not found:
            # Try even shorter match (first 15 chars)
            short = ps_norm[:15]
            pos = joined_norm.find(short)
            if pos > 0:
                split_positions.append(pos)
            else:
                _log(f"  [warn] Note at line {start + 1}: could not locate paragraph break "
                      f"for \"{ps_norm[:40]}...\". Manual review recommended.")
                return lines

    if not split_positions:
        return lines

    # Map char positions back to line indices
    # For each split position, find which content line it falls in
    split_line_indices = set()
    for sp in split_positions:
        for i, (char_start, line_idx, is_blank) in enumerate(line_boundaries):
            if is_blank:
                continue
            # Check if this split position falls within this line's text
            # Find the end of this line's contribution in joined_norm
            next_start = len(joined_norm)
            for j in range(i + 1, len(line_boundaries)):
                if not line_boundaries[j][2]:  # not blank
                    next_start = line_boundaries[j][0]
                    break
            if char_start <= sp < next_start:
                # The paragraph break should go before this line
                split_line_indices.add(line_idx)
                break

    if not split_line_indices:
        return lines

    # Now check: if the split point is in the MIDDLE of a line, we need
    # to split that line in two. If it's at the start of a line, just
    # insert a blank line before it.
    # For simplicity and safety, we work from bottom to top.
    fixes = 0
    for line_idx in sorted(split_line_indices, reverse=True):
        line_text = lines[line_idx]
        stripped = line_text.strip()
        prefix = ' ' * indent

        # Find which paragraph start matches within this line
        for sp_idx, sp in enumerate(split_positions):
            ps_norm = re.sub(r'\s+', ' ', para_starts[sp_idx + 1]).strip()
            # Try to find the paragraph start text in this line
            line_norm = re.sub(r'\s+', ' ', stripped)
            short_needle = ps_norm[:20]
            pos_in_line = line_norm.find(short_needle)
            if pos_in_line > 0:
                # Split this line at the paragraph boundary
                # Find the actual position in the original line text
                # Walk through the original stripped text matching normalized chars
                orig = stripped
                orig_pos = _find_orig_pos(orig, pos_in_line)
                if orig_pos is not None and orig_pos > 0:
                    before = prefix + orig[:orig_pos].rstrip()
                    after = prefix + orig[orig_pos:].lstrip()
                    lines[line_idx] = before + "\n" + prefix + "\n" + after
                    fixes += 1
                    break
            elif pos_in_line == 0:
                # Para starts at the beginning of this line — insert blank line before
                if line_idx > start + 1 and lines[line_idx - 1].strip():
                    lines.insert(line_idx, prefix)
                    fixes += 1
                    break

    if fixes:
        # Re-split lines since we may have inserted \n within lines
        result = "\n".join(lines)
        lines[:] = result.splitlines()
        _log(f"  [fix] Note at line {start + 1}: split {fixes} condensed paragraph(s) "
              f"(had {md_note['paragraph_count']}, prod has {prod_note['paragraphs']})")

    return lines


def _find_orig_pos(text: str, normalized_pos: int) -> Optional[int]:
    """Map a position in normalized (single-space) text back to the original text."""
    norm_i = 0
    in_space = False
    for orig_i, ch in enumerate(text):
        if ch in (' ', '\t'):
            if not in_space:
                norm_i += 1
                in_space = True
        else:
            if norm_i >= normalized_pos:
                return orig_i
            norm_i += 1
            in_space = False
    return None


def fix_image_indent(lines: List[str], md_img: dict, prod_img: dict) -> List[str]:
    """Fix an image's indentation based on prod structure."""
    line_idx = md_img["line"]
    current_indent = md_img["indent"]

    if prod_img["in_list"]:
        target_indent = _find_list_cont_indent(lines, line_idx)
        if target_indent is not None and target_indent != current_indent:
            _log(f"  [fix] Image at line {line_idx + 1}: indent {current_indent} -> {target_indent}")
            stripped = lines[line_idx].lstrip(' ')
            lines[line_idx] = ' ' * target_indent + stripped
    else:
        if current_indent > 0:
            _log(f"  [fix] Image at line {line_idx + 1}: indent {current_indent} -> 0 (top-level)")
            lines[line_idx] = lines[line_idx].lstrip(' ')

    return lines


def fix_orphaned_paragraph(lines: List[str], orphan: dict, prod_li_paragraphs: List[dict]) -> List[str]:
    """Fix a paragraph that escaped a list item by indenting it."""
    line_idx = orphan["line"]
    orphan_text = _normalize(orphan["text"])

    # Verify this paragraph belongs inside a list item in prod
    matched = False
    for lip in prod_li_paragraphs:
        if _normalize(lip["text"]).startswith(orphan_text[:30]) or orphan_text.startswith(_normalize(lip["text"])[:30]):
            matched = True
            break

    if not matched:
        return lines

    # Find the continuation indent from the preceding list item
    target_indent = _find_list_cont_indent(lines, line_idx)
    if target_indent is None or target_indent == 0:
        return lines

    _log(f"  [fix] Paragraph at line {line_idx + 1}: indent 0 -> {target_indent} "
          f"(\"{orphan['text'][:50]}...\")")
    lines[line_idx] = ' ' * target_indent + lines[line_idx]
    return lines


def fix_table_indent(lines: List[str], md_table: dict, prod_table: dict) -> List[str]:
    """Fix an HTML table's indentation within a list item.

    Strategy:
    1. Collapse multi-line <pre> blocks into single lines using &#10; entities
       (preserves code display while allowing proper indent)
    2. Re-indent all table lines to the list continuation indent
    3. Pad blank lines to prevent HTML block termination
    """
    if not prod_table["in_list"]:
        return lines

    start = md_table["start_line"]
    end = md_table["end_line"]

    target_indent = _find_list_cont_indent(lines, start)
    if target_indent is None or target_indent == 0:
        return lines

    # Check if any lines actually need fixing
    needs_fix = False
    for k in range(start, min(end + 1, len(lines))):
        line = lines[k]
        if not line.strip():
            # Blank lines inside tables can break HTML blocks
            needs_fix = True
            break
        current = len(line) - len(line.lstrip(' '))
        if current < target_indent:
            needs_fix = True
            break

    if not needs_fix:
        return lines

    # Step 1: Collapse multi-line <pre> blocks into single lines.
    # This replaces newlines within <pre> content with &#10; entities,
    # so code formatting is preserved when rendered while allowing
    # the entire table to be properly indented.
    tbl_lines = lines[start:end + 1]
    collapsed = _collapse_pre_blocks(tbl_lines)

    # Step 2: Re-indent all lines to target_indent
    indent_fixes = 0
    for k, line in enumerate(collapsed):
        current = len(line) - len(line.lstrip(' '))
        if not line.strip():
            # Blank line — pad to prevent HTML block break
            collapsed[k] = ' ' * target_indent
            indent_fixes += 1
        elif current < target_indent:
            collapsed[k] = ' ' * target_indent + line.lstrip(' ')
            indent_fixes += 1

    # Check if anything changed (collapse and/or indent)
    if collapsed != tbl_lines:
        lines[start:end + 1] = collapsed
        pre_collapsed = len(tbl_lines) - len(collapsed)
        parts = []
        if pre_collapsed > 0:
            parts.append(f"collapsed {pre_collapsed} <pre> line(s)")
        if indent_fixes > 0:
            parts.append(f"re-indented {indent_fixes} line(s) to indent {target_indent}")
        _log(f"  [fix] Table at lines {start + 1}-{end + 1}: {', '.join(parts)}")

    return lines


def _collapse_pre_blocks(tbl_lines: List[str]) -> List[str]:
    """Collapse multi-line <pre>...</pre> spans into single lines.

    Replaces real newlines with &#10; entities so code content renders
    correctly while staying on one indentable line.
    """
    pre_open_re = re.compile(r'<pre[\s>]', re.I)
    pre_close_re = re.compile(r'</pre>', re.I)

    result = []
    i = 0
    while i < len(tbl_lines):
        line = tbl_lines[i]

        # Check if this line opens a <pre> without closing it
        if pre_open_re.search(line) and not pre_close_re.search(line):
            # Multi-line <pre> — collapse into one line
            parts = [line.rstrip()]
            j = i + 1
            while j < len(tbl_lines):
                content = tbl_lines[j].rstrip()
                parts.append(content)
                if pre_close_re.search(tbl_lines[j]):
                    break
                j += 1
            # Join with &#10; to represent newlines in HTML
            # First part keeps its indent; subsequent parts are code content
            collapsed_line = parts[0]
            for part in parts[1:]:
                collapsed_line += "&#10;" + part
            result.append(collapsed_line)
            i = j + 1
        else:
            result.append(line)
            i += 1

    return result


def match_tables(md_tables: List[dict], prod_tables: List[dict]) -> List[Tuple[dict, dict]]:
    """Match md tables to prod tables by order."""
    pairs = []
    for i, md_t in enumerate(md_tables):
        if i < len(prod_tables):
            pairs.append((md_t, prod_tables[i]))
    return pairs


def _split_md_table_cells(row_text: str) -> List[str]:
    """Split a markdown table row into cell contents, respecting backtick spans."""
    s = row_text.strip()
    if s.startswith('|'):
        s = s[1:]
    if s.endswith('|'):
        s = s[:-1]

    cells = []
    current: List[str] = []
    in_code = False
    tick_count = 0
    i = 0
    while i < len(s):
        ch = s[i]
        if not in_code and ch == '`':
            j = i
            while j < len(s) and s[j] == '`':
                j += 1
            tick_count = j - i
            in_code = True
            current.append(s[i:j])
            i = j
            continue
        if in_code and ch == '`':
            j = i
            while j < len(s) and s[j] == '`':
                j += 1
            if j - i == tick_count:
                in_code = False
                current.append(s[i:j])
                i = j
                continue
            else:
                current.append(s[i:j])
                i = j
                continue
        if ch == '|' and not in_code:
            cells.append(''.join(current).strip())
            current = []
        else:
            current.append(ch)
        i += 1
    if current:
        cells.append(''.join(current).strip())
    return cells


def _md_cell_to_html(cell: str) -> str:
    """Convert markdown inline formatting in a table cell to HTML."""
    if not cell:
        return ""
    result = cell
    # Bold **text** → <strong>text</strong>
    result = re.sub(r'\*\*(.*?)\*\*', r'<strong>\1</strong>', result)

    # Inline code: handle ``` first, then `
    def _code_tag(code_text: str) -> str:
        if len(code_text) >= CODE_IN_TABLE_THRESHOLD:
            return f"<pre><code>{code_text}</code></pre>"
        return f"<code>{code_text}</code>"

    result = re.sub(r'```\s*(.*?)\s*```', lambda m: _code_tag(m.group(1)), result)
    result = re.sub(r'`([^`]+)`', lambda m: _code_tag(m.group(1).strip()), result)
    return result


def _clean_cell_html(td: Tag) -> str:
    """Convert a prod table cell to clean HTML, preserving structure tags.

    Searches the cell tree for meaningful content elements (<strong>, <pre>,
    <code>, <em>, <a>) while skipping UI chrome (buttons, styled wrappers).
    """
    # Skip UI chrome tags entirely
    _SKIP_TAGS = {"button", "svg", "path", "style", "script"}
    # Tags to recurse into (wrappers that hold real content)
    _WRAPPER_TAGS = {"div", "span", "p", "li", "td", "th"}

    parts: List[str] = []

    def _walk(node: Tag):
        for child in node.children:
            if isinstance(child, NavigableString):
                text = str(child).strip()
                if text:
                    parts.append(text)
            elif child.name in _SKIP_TAGS:
                continue
            elif child.name in ("strong", "b"):
                parts.append(f"<strong>{child.get_text()}</strong>")
            elif child.name in ("em", "i"):
                parts.append(f"<em>{child.get_text()}</em>")
            elif child.name == "pre":
                code = child.find("code")
                if code:
                    parts.append(f"<pre><code>{code.get_text()}</code></pre>")
                else:
                    parts.append(f"<pre>{child.get_text()}</pre>")
            elif child.name == "code":
                parts.append(f"<code>{child.get_text()}</code>")
            elif child.name == "a":
                href = child.get("href", "")
                parts.append(f'<a href="{href}">{child.get_text()}</a>')
            elif child.name in _WRAPPER_TAGS:
                _walk(child)
            # else: skip unknown tags (images, icons, etc.)

    _walk(td)
    return "".join(parts)


def _clean_table_html(table_tag: Tag, indent: int) -> List[str]:
    """Build clean, indented HTML lines from a prod BeautifulSoup table element."""
    prefix = ' ' * indent
    html = [f"{prefix}<table>", f"{prefix} <tbody>"]
    for tr in table_tag.find_all("tr"):
        html.append(f"{prefix}  <tr>")
        for td in tr.find_all(["td", "th"]):
            cell = _clean_cell_html(td)
            html.append(f"{prefix}   <td>{cell}</td>")
        html.append(f"{prefix}  </tr>")
    html.append(f"{prefix} </tbody>")
    html.append(f"{prefix}</table>")
    return html


def _match_pipe_table_to_prod(lines: List[str], md_pipe_table: dict,
                               prod_tables: List[dict]) -> Optional[dict]:
    """Find the prod table that matches a markdown pipe table by text content."""
    start = md_pipe_table["start_line"]
    end = md_pipe_table["end_line"]
    # Collect text from the MD pipe table (skip header if empty, skip separator)
    md_texts = []
    for k in range(start, end + 1):
        if k == start + 1:
            continue  # separator
        cells = _split_md_table_cells(lines[k])
        if k == start and all(not c for c in cells):
            continue
        for c in cells:
            # Strip markdown formatting for comparison
            clean = re.sub(r'`{1,3}', '', c)
            clean = re.sub(r'\*\*', '', clean)
            clean = re.sub(r'\s+', ' ', clean).strip()
            if clean:
                md_texts.append(clean[:40])

    if not md_texts:
        return None

    # Find the prod table whose text best matches
    best = None
    best_score = 0
    for pt in prod_tables:
        el = pt.get("element")
        if not el:
            continue
        prod_text = re.sub(r'\s+', ' ', el.get_text(strip=True))
        score = sum(1 for t in md_texts if t in prod_text)
        if score > best_score:
            best_score = score
            best = pt

    # Require at least half the cells to match
    if best and best_score >= max(1, len(md_texts) // 2):
        return best
    return None


def fix_md_pipe_table_to_html(lines: List[str], md_pipe_table: dict,
                               prod_table: Optional[dict] = None) -> List[str]:
    """Convert a markdown pipe table with long inline code to an HTML table.

    If a matching prod_table is provided, its HTML is used as the source of
    truth (preserving line breaks in code blocks).  Otherwise falls back to
    converting the markdown cells directly.
    """
    start = md_pipe_table["start_line"]
    end = md_pipe_table["end_line"]
    indent = md_pipe_table["indent"]

    # --- Preferred path: use prod HTML ---
    if prod_table and prod_table.get("element"):
        html_lines = _clean_table_html(prod_table["element"], indent)
        lines[start:end + 1] = html_lines
        _log(f"  [fix] Markdown table at lines {start + 1}-{end + 1}: "
             f"converted to HTML table (from prod)")
        return lines

    # --- Fallback: convert markdown cells ---
    prefix = ' ' * indent
    rows = []
    for k in range(start, end + 1):
        if k == start + 1:
            continue  # separator row
        cells = _split_md_table_cells(lines[k])
        if k == start and all(not c for c in cells):
            continue
        rows.append(cells)

    if not rows:
        return lines

    html_lines = [f"{prefix}<table>"]
    html_lines.append(f"{prefix} <tbody>")
    for row in rows:
        html_lines.append(f"{prefix}  <tr>")
        for cell in row:
            html_content = _md_cell_to_html(cell)
            html_lines.append(f"{prefix}   <td>{html_content}</td>")
        html_lines.append(f"{prefix}  </tr>")
    html_lines.append(f"{prefix} </tbody>")
    html_lines.append(f"{prefix}</table>")

    lines[start:end + 1] = html_lines
    _log(f"  [fix] Markdown table at lines {start + 1}-{end + 1}: "
         f"converted to HTML table (from markdown, no prod match)")
    return lines


def _find_list_cont_indent(lines: List[str], target_line: int) -> Optional[int]:
    """Find the continuation indent for the list item preceding target_line."""
    list_head = re.compile(r'^(\s*)([-*+]|\d+\.)\s+')
    for k in range(target_line - 1, -1, -1):
        if not lines[k].strip():
            continue
        m = list_head.match(lines[k])
        if m:
            base = len(m.group(1))
            marker_len = len(m.group(2)) + 1
            return base + marker_len
    return None


# ---------------------------------------------------------------------------
# Matching prod elements to md elements
# ---------------------------------------------------------------------------

def _normalize(s: str) -> str:
    return re.sub(r'\s+', ' ', s.strip().lower())[:60]


def match_notes(md_notes: List[dict], prod_notes: List[dict]) -> List[Tuple[dict, dict]]:
    """Match md notes to prod notes by order."""
    pairs = []
    for i, md_n in enumerate(md_notes):
        if i < len(prod_notes):
            pairs.append((md_n, prod_notes[i]))
    return pairs


def match_images(md_images: List[dict], prod_images: List[dict]) -> List[Tuple[dict, dict]]:
    """Match md images to prod images by order."""
    pairs = []
    for i, md_i in enumerate(md_images):
        if i < len(prod_images):
            pairs.append((md_i, prod_images[i]))
    return pairs


# ---------------------------------------------------------------------------
# Main fixer
# ---------------------------------------------------------------------------

def compare_structure(md: dict, prod: dict) -> List[str]:
    """Compare MD and prod structural elements, returning warning messages.

    Detects:
      - Heading count and text mismatches
      - Table count mismatches
      - Table column header and row count differences
      - Top-level paragraph text differences
    """
    warnings: List[str] = []

    # --- Headings ---
    # Prod headings are leveled-down in MD:
    #   prod h2 = MD frontmatter title
    #   prod h3 = MD h2, prod h4 = MD h3, etc.
    md_headings = md.get("headings", [])
    prod_headings = prod.get("headings", [])
    fm_title = md.get("frontmatter_title", "")

    # Separate prod h2 (should match frontmatter title) from subheadings
    prod_h2s = [h for h in prod_headings if h["level"] == 2]
    prod_sub = [h for h in prod_headings if h["level"] > 2]

    # Check prod h2 vs frontmatter title
    for ph2 in prod_h2s:
        ph2_text = re.sub(r'\s+', ' ', ph2["text"].strip().lower())
        fm_text = re.sub(r'\s+', ' ', fm_title.strip().lower())
        if fm_text and ph2_text != fm_text:
            warnings.append(
                f"  [struct] Page title differs: "
                f"MD frontmatter \"{fm_title[:40]}\" vs prod h2 \"{ph2['text'][:40]}\"")
        elif not fm_text:
            warnings.append(
                f"  [struct] Prod has h2 \"{ph2['text'][:40]}\" but MD has no frontmatter title")

    # Compare prod subheadings (h3+) with MD headings (level-shifted by -1)
    if len(md_headings) != len(prod_sub):
        warnings.append(
            f"  [struct] Heading count: MD has {len(md_headings)}, "
            f"prod has {len(prod_sub)} (excluding page title h2)")
        if md_headings:
            md_h_list = ", ".join(f'h{h["level"]}: "{h["text"][:40]}"' for h in md_headings)
            warnings.append(f"           MD headings: {md_h_list}")
        if prod_sub:
            prod_h_list = ", ".join(f'h{h["level"]}: "{h["text"][:40]}"' for h in prod_sub)
            warnings.append(f"           Prod headings: {prod_h_list}")
    else:
        for i, (md_h, prod_h) in enumerate(zip(md_headings, prod_sub)):
            # Expected: prod level - 1 = MD level (prod h3 → MD h2)
            expected_md_level = prod_h["level"] - 1
            if md_h["level"] != expected_md_level:
                warnings.append(
                    f"  [struct] Heading {i+1} level: MD h{md_h['level']} vs "
                    f"expected h{expected_md_level} (prod h{prod_h['level']}) "
                    f"(\"{md_h['text'][:40]}\")")
            md_text = re.sub(r'\s+', ' ', md_h["text"].strip().lower())
            prod_text = re.sub(r'\s+', ' ', prod_h["text"].strip().lower())
            if md_text != prod_text:
                warnings.append(
                    f"  [struct] Heading {i+1} text differs: "
                    f"MD \"{md_h['text'][:40]}\" vs prod \"{prod_h['text'][:40]}\"")

    # --- Tables ---
    md_tables = md.get("tables", [])
    prod_tables = prod.get("tables", [])
    if len(md_tables) != len(prod_tables):
        warnings.append(
            f"  [struct] Table count: MD has {len(md_tables)}, "
            f"prod has {len(prod_tables)}")
    # Compare matched tables
    for i, (md_t, prod_t) in enumerate(zip(md_tables, prod_tables)):
        md_cols = md_t.get("col_count", 0)
        prod_cols = prod_t.get("col_count", 0)
        if md_cols != prod_cols:
            warnings.append(
                f"  [struct] Table {i+1} columns: MD has {md_cols}, "
                f"prod has {prod_cols}")
        md_rows = md_t.get("row_count", 0)
        prod_rows = prod_t.get("row_count", 0)
        if md_rows != prod_rows:
            warnings.append(
                f"  [struct] Table {i+1} rows: MD has {md_rows}, "
                f"prod has {prod_rows}")
        # Compare headers
        md_hdrs = md_t.get("headers", [])
        prod_hdrs = prod_t.get("headers", [])
        for j, (mh, ph) in enumerate(zip(md_hdrs, prod_hdrs)):
            mh_norm = re.sub(r'\s+', ' ', mh.strip().lower())
            ph_norm = re.sub(r'\s+', ' ', ph.strip().lower())
            if mh_norm != ph_norm:
                warnings.append(
                    f"  [struct] Table {i+1} header col {j+1}: "
                    f"MD \"{mh[:40]}\" vs prod \"{ph[:40]}\"")

    # --- Top-level paragraphs ---
    md_paras = md.get("paragraphs", [])
    prod_paras = prod.get("paragraphs", [])

    def _norm_para(text: str) -> str:
        """Normalize paragraph text for comparison — strip markdown/HTML formatting."""
        t = re.sub(r'\[([^\]]*)\]\([^)]*\)', r'\1', text)   # [text](url) → text
        t = re.sub(r'\*\*([^*]*)\*\*', r'\1', t)            # **bold** → bold
        t = re.sub(r'`([^`]*)`', r'\1', t)                  # `code` → code
        t = re.sub(r'<[^>]+>', '', t)                        # strip HTML tags
        t = re.sub(r'\s+', '', t.strip().lower())            # collapse all whitespace
        return t

    if len(md_paras) != len(prod_paras):
        warnings.append(
            f"  [struct] Paragraph count: MD has {len(md_paras)}, "
            f"prod has {len(prod_paras)}")

    # Content-based matching: for each MD paragraph, find best match in prod.
    # This avoids cascading mismatches when counts differ by 1-2.
    prod_norms = [_norm_para(p["text"]) for p in prod_paras]
    prod_matched = [False] * len(prod_paras)
    md_unmatched = []
    for md_p in md_paras:
        md_norm = _norm_para(md_p["text"])
        found = False
        for j, pn in enumerate(prod_norms):
            if not prod_matched[j] and md_norm[:30] == pn[:30]:
                prod_matched[j] = True
                # Check for longer-range text differences
                if md_norm[:80] != pn[:80]:
                    warnings.append(
                        f"  [struct] Paragraph text differs:")
                    warnings.append(
                        f"           MD:   \"{md_p['text'][:60]}...\"")
                    warnings.append(
                        f"           Prod: \"{prod_paras[j]['text'][:60]}...\"")
                found = True
                break
        if not found:
            md_unmatched.append(md_p)

    prod_unmatched = [prod_paras[j] for j in range(len(prod_paras))
                      if not prod_matched[j]]

    for md_p in md_unmatched:
        warnings.append(
            f"  [struct] Paragraph in MD not found in prod: "
            f"\"{md_p['text'][:60]}...\"")
    for prod_p in prod_unmatched:
        warnings.append(
            f"  [struct] Paragraph in prod not found in MD: "
            f"\"{prod_p['text'][:60]}...\"")

    return warnings


def fix_md_file(md_path: str, prod_url: str, dry_run: bool = False) -> dict:
    """
    Fix known conversion issues in an existing .md file.

    Returns a dict with counts of fixes applied and a 'log' key
    containing the messages emitted for this page.
    """
    # Snapshot the log so we can capture this page's messages
    log_start = len(_log_lines)

    _log(f"\nFixing: {md_path}")
    _log(f"  Prod: {prod_url}")

    # Read the .md file
    with open(md_path, "r", encoding="utf-8") as f:
        original = f.read()
    lines = original.splitlines()

    # Fetch and parse prod HTML
    _log("  Fetching prod HTML...")
    container = fetch_prod_html(prod_url)
    if not container:
        _log("  [error] Could not fetch prod HTML. Aborting.")
        return {"errors": 1}

    prod = extract_prod_structure(container)
    md = parse_md_structure(lines)

    stats = {"note_indent": 0, "note_paragraphs": 0, "image_indent": 0,
             "orphaned_para": 0, "table_indent": 0, "md_table_to_html": 0,
             "errors": 0}

    # Fix orphaned paragraphs first (before other fixes shift line numbers)
    for orphan in reversed(md["orphaned_paragraphs"]):
        old_lines = lines[:]
        lines = fix_orphaned_paragraph(lines, orphan, prod["li_paragraphs"])
        if lines != old_lines:
            stats["orphaned_para"] += 1

    # Re-parse after orphan fixes (line numbers may have shifted due to indent changes)
    md = parse_md_structure(lines)

    # Fix notes
    note_pairs = match_notes(md["notes"], prod["notes"])
    for md_note, prod_note in reversed(note_pairs):  # reversed to preserve line numbers
        old_lines = lines[:]
        lines = fix_note_indent(lines, md_note, prod_note)
        if lines != old_lines:
            stats["note_indent"] += 1
        old_lines = lines[:]
        lines = fix_note_paragraphs(lines, md_note, prod_note)
        if lines != old_lines:
            stats["note_paragraphs"] += 1

    # Fix images
    img_pairs = match_images(md["images"], prod["images"])
    for md_img, prod_img in reversed(img_pairs):
        old_lines = lines[:]
        lines = fix_image_indent(lines, md_img, prod_img)
        if lines != old_lines:
            stats["image_indent"] += 1

    # Fix tables
    # Re-parse to get fresh line numbers after previous fixes
    md = parse_md_structure(lines)
    tbl_pairs = match_tables(md["tables"], prod["tables"])
    for md_tbl, prod_tbl in reversed(tbl_pairs):
        old_lines = lines[:]
        lines = fix_table_indent(lines, md_tbl, prod_tbl)
        if lines != old_lines:
            stats["table_indent"] += 1

    # Convert markdown pipe tables with long code to HTML
    # Re-parse to pick up md_pipe_tables with fresh line numbers
    md = parse_md_structure(lines)
    for md_pipe_tbl in reversed(md["md_pipe_tables"]):
        old_lines = lines[:]
        prod_match = _match_pipe_table_to_prod(lines, md_pipe_tbl, prod["tables"])
        lines = fix_md_pipe_table_to_html(lines, md_pipe_tbl, prod_match)
        if lines != old_lines:
            stats["md_table_to_html"] += 1

    # Structural comparison — detect mismatches between MD and prod
    md_final = parse_md_structure(lines)
    struct_warnings = compare_structure(md_final, prod)
    stats["structural_warnings"] = len(struct_warnings)
    if struct_warnings:
        _log("")
        for w in struct_warnings:
            _log(w)

    # Write fixes
    result = "\n".join(lines)
    total_fixes = sum(v for k, v in stats.items() if k not in ("errors", "log", "structural_warnings"))
    if result != original:
        if dry_run:
            _log(f"\n  [dry-run] Would fix: {total_fixes} issues")
        else:
            with open(md_path, "w", encoding="utf-8") as f:
                f.write(result)
            _log(f"\n  Applied {total_fixes} fix(es). File updated.")
    else:
        if struct_warnings:
            _log(f"\n  No auto-fixes needed, but {len(struct_warnings)} structural warning(s) found.")
        else:
            _log("\n  No fixes needed.")

    stats["log"] = _log_lines[log_start:]
    return stats


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def resolve_md_path(prod_url: str) -> Optional[str]:
    """Derive the local .md file path from a prod URL.

    Example:
      https://docs.uipath.com/apps/automation-cloud/latest/user-guide/apps-feature-availability
      -> apps-feature-availability.md  (search current dir and subdirs)
    """
    import urllib.parse as up
    path = up.urlparse(prod_url).path.rstrip("/")
    slug = path.split("/")[-1] if path else None
    if not slug:
        return None
    filename = f"{slug}.md"

    # 1. Check current directory
    if os.path.isfile(filename):
        return filename

    # 2. Check mirror path (product/delivery/version/guide/slug.md)
    segments = [s for s in path.split("/") if s]
    if len(segments) >= 2:
        mirror = os.path.join(*segments[:-1], filename)
        if os.path.isfile(mirror):
            return mirror

    # 3. Recursive search from cwd
    for root, _dirs, files in os.walk("."):
        if filename in files:
            return os.path.join(root, filename)

    return None


def _write_report(report_path: str, fixed_pages: List[dict], summary: str):
    """Write a report file listing only the fixed pages and their details."""
    from datetime import datetime
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(f"fix-md.py report — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write("=" * 60 + "\n\n")
        if not fixed_pages:
            f.write("No files needed fixing.\n")
        else:
            f.write(f"{len(fixed_pages)} file(s) with fixes or warnings:\n\n")
            for page in fixed_pages:
                f.write(f"--- {page['md_path']} ---\n")
                f.write(f"    Prod: {page['url']}\n")
                for line in page["log"]:
                    # Include [fix], [warn], and [struct] lines + continuation lines
                    stripped = line.strip()
                    if (stripped.startswith("[fix]") or stripped.startswith("[warn]")
                            or stripped.startswith("[struct]")
                            or stripped.startswith("MD headings:") or stripped.startswith("Prod headings:")
                            or stripped.startswith("MD:") or stripped.startswith("Prod:")):
                        # Skip the "Prod: https://..." info line (already shown above)
                        if stripped.startswith("Prod: http"):
                            continue
                        f.write(f"    {stripped}\n")
                f.write("\n")
        f.write(summary + "\n")
    _log(f"  Report written to: {report_path}")


def fix_guide(start_url: str, dry_run: bool = False,
              start_page: int = 0, end_page: int = 0) -> dict:
    """Crawl all pages in a guide and fix each corresponding .md file.

    Args:
        start_page: 1-based start index (0 = from beginning).
        end_page: 1-based end index (0 = no limit).
    """
    # Discover up to end_page pages (or all if 0)
    urls = discover_guide_urls(start_url, max_pages=end_page)
    # Slice to the requested range
    if start_page > 0:
        urls = urls[start_page - 1:]
        _log(f"  Processing pages {start_page}-{start_page + len(urls) - 1}\n")

    totals = {"pages": 0, "fixed": 0, "skipped": 0, "errors": 0}
    fixed_pages = []

    for url in urls:
        md_path = resolve_md_path(url)
        if not md_path:
            slug = url.rstrip("/").split("/")[-1]
            _log(f"\n  [skip] No .md file found for {slug}")
            totals["skipped"] += 1
            continue

        totals["pages"] += 1
        stats = fix_md_file(md_path, url, dry_run=dry_run)
        if stats.get("errors"):
            totals["errors"] += 1
        elif sum(v for k, v in stats.items() if k not in ("errors", "log", "structural_warnings")) > 0:
            totals["fixed"] += 1
            fixed_pages.append({"md_path": md_path, "url": url, "log": stats.get("log", [])})
        elif stats.get("structural_warnings", 0) > 0:
            # Include pages with only structural warnings in the report
            fixed_pages.append({"md_path": md_path, "url": url, "log": stats.get("log", [])})

        time.sleep(THROTTLE_SECONDS)

    summary = (f"Guide summary: {totals['pages']} pages processed, "
               f"{totals['fixed']} fixed, {totals['skipped']} skipped, "
               f"{totals['errors']} errors")
    _log(f"\n{'=' * 50}")
    _log(summary)

    # Derive report filename from guide slug
    parsed = urllib.parse.urlparse(start_url)
    path_parts = [s for s in parsed.path.strip("/").split("/") if s]
    guide_slug = "-".join(path_parts[:2]) if len(path_parts) >= 2 else "guide"
    report_path = f"~fix-md-report-{guide_slug}.txt"
    _write_report(report_path, fixed_pages, summary)

    return totals


def main():
    parser = argparse.ArgumentParser(
        description="Fix known conversion bugs in .md files generated by md_maker.py"
    )
    parser.add_argument("prod_url", help="Production URL (docs.uipath.com)")
    parser.add_argument("md_file", nargs="?", default=None,
                        help="Path to the .md file (auto-detected from URL if omitted)")
    parser.add_argument("--crawl", action="store_true",
                        help="Crawl all pages in the guide and fix each one")
    parser.add_argument("--limit", type=str, default="0",
                        help="Pages to process: N (first N) or M-N (range). E.g. --limit 10, --limit 10-20")
    parser.add_argument("--dry-run", action="store_true",
                        help="Show what would be fixed without modifying the file")
    args = parser.parse_args()

    if args.crawl:
        # Parse --limit: "0" = all, "N" = first N, "M-N" = range
        start_page, end_page = 0, 0
        if "-" in args.limit:
            parts = args.limit.split("-", 1)
            start_page, end_page = int(parts[0]), int(parts[1])
        else:
            end_page = int(args.limit)
        totals = fix_guide(args.prod_url, dry_run=args.dry_run,
                           start_page=start_page, end_page=end_page)
        if totals["errors"]:
            sys.exit(1)
        return

    md_file = args.md_file
    if not md_file:
        md_file = resolve_md_path(args.prod_url)
        if not md_file:
            slug = args.prod_url.rstrip("/").split("/")[-1]
            print(f"Error: could not find {slug}.md in current directory or subdirectories.")
            sys.exit(1)
        print(f"  Resolved .md file: {md_file}")

    if not os.path.isfile(md_file):
        print(f"Error: file not found: {md_file}")
        sys.exit(1)

    stats = fix_md_file(md_file, args.prod_url, dry_run=args.dry_run)

    # Write report for single-page mode too
    total_fixes = sum(v for k, v in stats.items() if k not in ("errors", "log", "structural_warnings"))
    struct_warns = stats.get("structural_warnings", 0)
    if total_fixes > 0 or struct_warns > 0:
        slug = args.prod_url.rstrip("/").split("/")[-1]
        report_path = f"~fix-md-report-{slug}.txt"
        fixed_pages = [{"md_path": md_file, "url": args.prod_url, "log": stats.get("log", [])}]
        parts = []
        if total_fixes > 0:
            parts.append(f"{total_fixes} fix(es) applied")
        if struct_warns > 0:
            parts.append(f"{struct_warns} structural warning(s)")
        summary = f"Single page: {', '.join(parts)}"
        _write_report(report_path, fixed_pages, summary)

    if stats.get("errors"):
        sys.exit(1)


if __name__ == "__main__":
    main()
